version: "3"

services:
  web:
    image: nginx:latest
    env_file: .env
    ports:
      - "${HTTP_BINDED_PORT}:80"
      - "${HTTPS_BINDED_PORT}:443"
    tty: true
    volumes:
      - .:/var/www/html
      - ./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/nginx/ssl:/etc/nginx/ssl
      - ./.docker/config/nginx/logs:/var/log/nginx
      - ${NGINX_CONFIG_FILE}:/etc/nginx/sites-enabled/default.conf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    depends_on:
      - php
      - mysql
    networks:
      ## BEGIN webserver_network_ip ##
      - back
      ## END webserver_network_ip ##

  php:
    image: summasolutions/php:${PHP_VERSION}
    ports:
      - 9001
    volumes:
      - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      #- ./.docker/config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
      - ./.docker/config/php/ext-ioncube.ini:/usr/local/etc/php/conf.d/10-php-ext-ioncube.ini
      - ./.docker/config/php/volumes/php-fpm/logs:/var/log/php-fpm
      - ./.docker/config/php/volumes/logs:/var/log/supervisor
      - .:/var/www/html
      #- .docker/config/php/crontab/cronfile:/etc/cron.d/cronfile
      #- .docker/config/php/supervisor/conf.d:/etc/supervisor/conf.d
    env_file: .env
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    user: www-data
    links:
      - mysql
    networks:
      - back

  mysql:
    image: mariadb:${MYSQL_VERSION}
    env_file: .env
    ports:
      - "${DATABASE_BINDED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      SERVICE_NAME: mysql
    volumes:
      - "./.docker/config/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./.docker/config/mysql/dumps:/dumps"
      - "${MYSQL_CONFIG_FILE}:/etc/mysql/conf.d"
      - gm-volume-db:/var/lib/mysql:delegated
    networks:
      - back

  phpc:
    build:
      context: ./.docker/config/php-cli
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - .docker/config/php/phpc.ini:/usr/local/etc/php/php.ini-production
    stdin_open: true
    working_dir: /var/www/html
    tty: true
    networks:
      - back

  redis:
    hostname: redis.magento2.docker
    image: 'redis:5.0'
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      back:
        aliases:
          - redis.magento2.docker

  elasticsearch:
    hostname: elasticsearch.magento2.docker
    #image: 'magento/magento-cloud-docker-opensearch:2.5-1.4.0'
    image: 'magento/magento-cloud-docker-elasticsearch:7.11-1.2.4'
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      - bootstrap.memory_lock=true
      - DISABLE_SECURITY_PLUGIN=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9600:9600
    networks:
      back:
        aliases:
          - elasticsearch.magento2.docker
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - back

volumes:
  gm-volume-db:
  rabbitmqdata:

networks:
  ## BEGIN networks ##
  back:
    driver: bridge
  ## END networks ##

